### ISSUE TITLE
Sửa form đăng kí trên website .com

### ISSUE THREAD

**Issue by tanlucbui** [caresvn/odinland.com#6]
Anh sửa form đăng kí theo ý anh Minh nhé. Em không biết ý ảnh muốn sửa như thế nào.
![code website](https://user-images.githubusercontent.com/44955460/48968144-46f55080-f01d-11e8-9f5b-bff666cbddc2.PNG)

**Comment by khoipro** [comment]
Anh đã thu nhỏ form lại rồi @tanlucbui B
