### ISSUE TITLE
Sửa dự án liên quan trong .com

### ISSUE THREAD

**Issue by tanlucbui** [caresvn/odinland.com#7]
Ở dưới mỗi thông tin của mỗi dự án điều có hiển thị dự án liên quan. Anh xem nó bị lỗi gì mà không hiển thị ra được.
![0-02-06-b4878a743121866a9fa0e4efa2cda75f1ed17b8ffa743da4e6d5d6978397678f_d990f1f](https://user-images.githubusercontent.com/44955460/49002628-b6d91780-f192-11e8-861e-5e43dbc477dd.jpg)

**Comment by tanlucbui** [comment]
Anh xem thêm chỗ địa điểm của .com

Em không chia được nội dung của địa điểm thành 3 tabs văn phòng cho thuê, văn phòng dịch vụ và mặt bằng thương mại được. Khi em đổi nội dung phần địa điểm của tabs văn phòng cho thuê thì 2 tabs còn lại cũng đổi theo.
![hinh can sua](https://user-images.githubusercontent.com/44955460/49003193-1257d500-f194-11e8-9f0b-6a5aedad2ec4.PNG)

**Comment by khoipro** [comment]
> Anh xem thêm chỗ địa điểm của .com
> 
> Em không chia được nội dung của địa điểm thành 3 tabs văn phòng cho thuê, văn phòng dịch vụ và mặt bằng thương mại được. Khi em đổi nội dung phần địa điểm của tabs văn phòng cho thuê thì 2 tabs còn lại cũng đổi theo.

Lỗi này anh không hiểu em nói gì, tab nào nhỉ @tanlucbui ???

**Comment by khoipro** [comment]
Lỗi còn lại đã fix rồi @tanlucbui

**Comment by tanlucbui** [comment]
Tức là 3 tabs: văn phòng dịch vụ, văn phòng cho thuê và mặt bằng thương mại có chung 1 nội dung trong phần địa điểm. 
Anh vào thử một bài viết tòa nhà văn phòng nào đó. Anh kéo xuống dưới cùng phía bên trái là nội dung, bên phải là cái Map. Nội dung phía bên trái nó định dạng sẵn cho 3 tabs luôn. Khi chuyển qua tabs khác thì nội dung vẫn vậy ko thay đổi. E ko sửa được phần này.

**Comment by khoipro** [comment]
Cái này đã update thêm các mục nhập trong wp-admin > Địa điểm cho Văn phòng dịch vụ và Mặt bằng thương mại nhé @tanlucbui.

<img width="427" alt="screenshot at dec 02 22-40-38" src="https://user-images.githubusercontent.com/10395311/49341652-501c9800-f683-11e8-8857-41366ce3fb00.png">
