### ISSUE TITLE
Lỗi mất chân trang ở bên mục mặt bằng

### ISSUE THREAD

**Issue by tanlucbui** [caresvn/odinland.com#8]
Anh xem sửa lại lỗi này giúp em với.
![0-02-06-99ab0c8d3a2fb7bba380701ae397d74bf06c6538987dc56103836aad27f7a65c_ef924637](https://user-images.githubusercontent.com/44955460/49262226-22173800-f478-11e8-84a1-f27ac14fd0e4.jpg)

**Comment by khoipro** [comment]
Đã fix rồi.
