### ISSUE TITLE
Lỗi ngày 01/12/2018

### ISSUE THREAD

**Issue by tanlucbui** [caresvn/odinland.com#9]
Còn Slide ảnh trong mỗi bài viết anh fix lại như cũ đi. Cái mới Mr Minh ko chịu.
Với lại trên phiên bản mobile còn lỗi ngay chỗ slide ảnh.
Link:
https://odinland.com/van-phong/van-phong-cho-thue-toa-nha-tnr-tower

Tất cả các bài khác cũng vậy.

**Comment by khoipro** [comment]
@tanlucbui em nói chuyện cũ mới anh không hình dung được. Cũ là như thế nào? Em nói như vậy anh không sửa được vì anh không biết design cũ ra sao.

Trên mobile anh xem đâu có lỗi nhỉ???

Issue thì em nên đổi tiêu đề issue cho anh theo ngày tháng năm nhé để sau dễ tracking.
Ví dụ: "Lỗi ngày 01/12/2018" để anh còn nắm được lỗi nào phát sinh và báo giá bổ sung.

<img width="231" alt="screenshot at dec 02 22-29-46" src="https://user-images.githubusercontent.com/10395311/49341583-dfc14700-f681-11e8-8fda-26792c3f6efe.png">
